---
ansible_network_os: ios
ansible_connection: ansible.netcommon.network_cli
ansible_user: fyc
ansible_password: cisco123
ansible_become: yes
ansible_become_method: enable
ansible_become_password: fyc
configs_dir: configuration
